[package]
name = "command_runner"
version = "0.1.0"
authors = ["DevMaster"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.101"
serde_json = "1.0.40"